// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:string):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function GetServers():Promise<Array<main.Server>>;

export function SaveServer(arg1:main.Server,arg2:string,arg3:string):Promise<void>;
