// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function SaveServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveServer'](arg1, arg2, arg3);
}
